INSERT INTO tb_category (name, created_At) VALUES ('Smartphones', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Home Decor', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Kitchenware', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Fitness Gear', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Pet Supplies', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Sports Equipment', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Gardening Tools', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Office Supplies', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Travel Accessories', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Musical Instruments', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Art Supplies', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Party Supplies', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Automotive Parts', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Fashion Accessories', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Home Appliances', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Outdoor Gear', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Board Games', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Watches', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Lighting', CURRENT_TIMESTAMP);
INSERT INTO tb_category (name, created_At) VALUES ('Tools & Hardware', CURRENT_TIMESTAMP);
